services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"

  agent:
    links:
      - server
    build:
      context: .
      dockerfile: agent/Dockerfile

